version: "3"

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/padam/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/padam/data/mariadb

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 433:443
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    expose:
      - 9000
